run:
	npm start

dev:
	npm run dev

migrate:
	npm run migrate

rollback:
	npm run rollback

seek:
	npm run seed

test-setup:
	jest ./src/test/setup.tests.js

test-app:
	jest ./src/test/app.test.js

test-api:
	jest ./src/test/api.test.js

test-api-states:
	jest ./src/test/states.test.js
